"""Change account_id to BigInteger

Revision ID: 527f738e439e
Revises: 95200674ddc2
Create Date: 2025-09-09 12:02:51.350356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527f738e439e'
down_revision: Union[str, Sequence[str], None] = '95200674ddc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administration_id'), table_name='administration')
    op.drop_table('administration')
    op.create_unique_constraint(None, 'cities', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='unique')
    op.create_table('administration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('administration_pkey')),
    sa.UniqueConstraint('account_id', name=op.f('administration_account_id_key'))
    )
    op.create_index(op.f('ix_administration_id'), 'administration', ['id'], unique=False)
    # ### end Alembic commands ###
