"""Add is_active and active_until columns to drivers

Revision ID: 6bcef974ff11
Revises: 
Create Date: 2025-09-07 21:51:53.068544

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6bcef974ff11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('is_active', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'drivers', ['phone'])
    op.create_unique_constraint(None, 'drivers', ['car_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'is_active')
    # ### end Alembic commands ###
